spring:
  application:
    name: config
  cloud:
    config:
      password: counect
      username: counect
      server:
        git:
          uri: http://172.16.1.200/yan.ma/staging-config.git
          password: lijing31370
          username: yan.ma
          force-pull: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/,http://localhost:8082/eureka/
server:
  port: 8888