spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: http://172.16.1.200/yan.ma/staging-config.git
          password: lijing31370
          username: yan.ma
          force-pull: true
          search-paths: '{application}'
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8081/eureka/,http://peer2:8082/eureka/
  instance:
    instance-id: '[${spring.application.name}]${spring.cloud.client.ipAddress}:${server.port}'
    hostname: peer1
server:
  port: 8888