spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: http://172.16.1.200/yan.ma/staging-config.git
          password: lijing31370
          username: yan.ma
          force-pull: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.101:8761/eureka/,http://192.168.1.102:8761/eureka/
  instance:
    instance-id: '[${spring.application.name}]${spring.cloud.client.ipAddress}:${server.port}'
server:
  port: 8888